### ISSUE TITLE
Is MapView.py used?

### ISSUE THREAD

**Issue by jmcfarland-swri** [mh-swri/NASA_ULI_InfoFusion#10]
@mh-swri As far as I can tell, `MapView.py` is not used anywhere in PARA_ATM, at least in the nats-v17 branch.  Do you know what it is for and whether it is still needed?

**Comment by mh-swri** [comment]
MapView is the legacy method for the GUI and produced a static html doc. It is no longer needed.

**Comment by jmcfarland-swri** [comment]
Roger that.  How about QueryOntology?  It doesn't look like it is used either.

**Comment by mh-swri** [comment]
QueryOntology is in the same category.

**Comment by jmcfarland-swri** [comment]
OK, thanks I will remove these modules then.  I assume that the files under Map/web can be removed also?

**Comment by jmcfarland-swri** [comment]
Removed in https://github.com/jmcfarland-swri/NASA_ULI_InfoFusion/commit/51296cb82501db844d0188e6d57dd1546c5d34eb
