### ISSUE TITLE
readIFF parallel processing

### ISSUE THREAD

**Issue by jmcfarland-swri** [mh-swri/NASA_ULI_InfoFusion#11]
@mh-swri Do you have any testing on runtimes for readIFF with and without parallel processing?  I'm wondering how much benefit that is provided, as it makes the code quite a bit harder to follow.

**Comment by mh-swri** [comment]
The speedup factor was ~5x. This was mainly beneficial for processing datasets with over 1 hour of data.

**Comment by jmcfarland-swri** [comment]
Having had a chance to see the specification of the IFF file format, a couple of things I notice about the code:
- It assumes a particular relationship between where the header entries (recordType=2) appear relative to the data that need to be extracted
- It doesn't seem to account for the fact that each recordType can have different columns
- In general, you want to avoid using a `for` loop to iterate over rows in a data frame.  This is probably the source of the performance issues.

The way that I would read this type of file is basically:
```python
with open(filename, 'r') as f:
    data = np.array(f.readlines())

line_record_types = np.array([int(line.split(',')[0]) for line in data])

# Map record type to data frame
data_frames = dict()
for record_type in np.unique(line_record_types):
    lines = data[line_record_types == record_type]
    string_data = io.StringIO( '\n'.join(lines) )
    data_frames[record_type] = pd.read_csv(string_data, header=None, names=cols[record_type], low_memory=False, na_values='?')
```
where `cols` is a dictionary mapping each record type to the associated column names.  This has the advantage that it will produce a separate data frame for each individual record type.  Because there is no iteration over rows, this is very fast (takes just a few seconds to process a sample 150 MB IFF file), so there is no need for parallel processing.

**Comment by jmcfarland-swri** [comment]
With new approach in https://github.com/jmcfarland-swri/NASA_ULI_InfoFusion/commit/8bb70b89c474e8f381f1f1d3deb2393723cf88fc, parallel processing not necssary
