### ISSUE TITLE
readIFF "value change"

### ISSUE THREAD

**Issue by jmcfarland-swri** [mh-swri/NASA_ULI_InfoFusion#12]
In readIFF.py, this line:
https://github.com/mh-swri/NASA_ULI_InfoFusion/blob/229f0a7381e3dc0394774066aa5163882400b941/src/PARA_ATM/Commands/readIFF.py#L124
calls this function:
https://github.com/mh-swri/NASA_ULI_InfoFusion/blob/229f0a7381e3dc0394774066aa5163882400b941/src/PARA_ATM/Commands/readIFF.py#L14-L18
to replace any data in the specified columns (`floats`) that can't be converted to a float with the value -100.

@mh-swri is there anything special about the value -100?  Would it make more sense to use `np.nan` to denote a missing value, or would that break other parts of the code?

**Comment by mh-swri** [comment]
np.nan cannot be passed to the pd.interpolate method. However, it makes more sense to replace the missing values (-100 -> np.nan) or remove them at the end of the readIFF module rather than in the getIFFdata function.

**Comment by jmcfarland-swri** [comment]
So what is the intent of the use of `DataFrame.interpolate` in the following?
https://github.com/mh-swri/NASA_ULI_InfoFusion/blob/229f0a7381e3dc0394774066aa5163882400b941/src/PARA_ATM/Commands/readIFF.py#L131-L135

I believe pandas interpolate is used to fill in missing values (nan).  It seems like that is exactly what you would want to do with data that were missing originally, right?

**Comment by mh-swri** [comment]
A full column of np.nan is the problem I ran into. Maybe there is a more graceful handling of that case.

**Comment by jmcfarland-swri** [comment]
OK.  It's not an error to call `Series.interpolate` on a column of only nan's though.  The result will still be nan's.  It seems to be it would be better to just use nan's to represent the missing values from the start.  If there is nothing to interpolate, they will stay as nan's.

**Comment by jmcfarland-swri** [comment]
Ideally we would use the `na_values` option to `pd.read_csv` to tell it what other keys indicate missing values (e.g., "?").  If we know beforehand what is used in IFF to indicate missing values, there probably wouldn't be any need for the try/except block that converts to float.

**Comment by jmcfarland-swri** [comment]
On https://github.com/jmcfarland-swri/NASA_ULI_InfoFusion/commit/8bb70b89c474e8f381f1f1d3deb2393723cf88fc, this is addressed by using `na_values='?'`.  If other problems occur with missing values, they can be addressed as they come up.
